<a href="https://colab.research.google.com/github/Leos1999/Hackathons/blob/master/LTFS_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
from zipfile import ZipFile
f = 'train_aox2Jxw (2).zip'
with ZipFile(f,'r') as zip:
  zip.extractall()


In [0]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout,BatchNormalization
import csv

data = pd.read_csv('train.csv')
data = data.dropna()
pro_data = data.iloc[:,[3,9,19,33,34,35,36,37,38,39,4,5,6,11,12,40]]

In [0]:

# X = pro_data.iloc[:,:15].values
# y = pro_data.iloc[:,15].values
X = pro_data.iloc[:,:16].values
#X = np.array(X, dtype=object)
np.random.shuffle(X)

y = X[:,15]
X = X[:,:15]

for row in X:
    string = row[7]
    string = string.replace('yrs','')
    string = string.replace('mon','')
    s = string.split()
    string = int(s[0])*12+int(s[1])
    row[7] = string
    string = row[8]
    string = string.replace('yrs','')
    string = string.replace('mon','')
    s = string.split()
    string = int(s[0])*12+int(s[1])
    row[8] = string
print(X[1])
y[1]

[74.99 'Salaried' 0 0 0 0 0 0 0 0 78 16845 51 4 104]


0

In [0]:
emp = []
e = {}
for row in X:
    if row[1] not in emp:
        emp.append(row[1])
for i in range(len(emp)):
    e[emp[i]] = i
print(e)
for row in X:
    for k,v in e.items():
        if k==row[1]:
            row[1]=v
X[1000]

{'Self employed': 0, 'Salaried': 1}


array([68.4, 1, 17, 0, 0, 1, 0, 5, 5, 0, 48, 15912, 45, 5, 2847],
      dtype=object)

In [0]:
r10 = []
r_10 = {}
for row in X:
    if row[10] not in r10:
        r10.append(row[10])
for i in range(len(r10)):
    r_10[r10[i]] = i
r11 = []
r_11 = {}
for row in X:
    if row[11] not in r11:
        r11.append(row[11])
for i in range(len(r11)):
    r_11[r11[i]] = i
r12 = []
r_12 = {}
for row in X:
    if row[12] not in r12:
        r12.append(row[12])
for i in range(len(r12)):
    r_12[r12[i]] = i
r13 = []
r_13 = {}
for row in X:
    if row[13] not in r13:
        r13.append(row[13])
for i in range(len(r13)):
    r_13[r13[i]] = i
r14 = []
r_14 = {}
for row in X:
    if row[14] not in r14:
        r14.append(row[14])
for i in range(len(r14)):
    r_14[r14[i]] = i


In [0]:
# from numpy import array
# from numpy import argmax
# from keras.utils import to_categorical
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()

# #10
# r10=[]
# r_10={}
# for row in X:
#   if row[10] not in r10:
#     r10.append(row[10])
#   if row[11] not in r10:
#     r10.append(row[11])
#   if row[12] not in r10:
#     r10.append(row[12])
#   if row[13] not in r10:
#     r10.append(row[13])
#   if row[14] not in r10:
#     r10.append(row[14])
# a_r10 = array(r10)
# i_r10 = label_encoder.fit_transform(a_r10)
# e_r10 = to_categorical(i_r10,num_classes=len(r10))
# for i in range(len(r10)):
#   r_10[r10[i]] = list(e_r10[i])


In [0]:
# for row in X:
#   for k,v in r_10.items():
#         if k==row[10]:
#             row[10]=v
#             break
#   for k,v in r_10.items():
#         if k==row[11]:
#             row[11]=v
#             break
#   for k,v in r_10.items():
#         if k==row[12]:
#             row[12]=v
#             break
#   for k,v in r_10.items():
#         if k==row[13]:
#             row[13]=v
#             break
#   for k,v in r_10.items():
#         if k==row[14]:
#             row[14]=v
#             break


In [0]:
# from numpy import array
# from numpy import argmax
# from keras.utils import to_categorical
# from sklearn.preprocessing import LabelEncoder
# label_encoder = LabelEncoder()

# #10
# r10=[]
# r_10={}
# for row in X:
#   if row[10] not in r10:
#     r10.append(row[10]) 
# a_r10 = array(r10)
# i_r10 = label_encoder.fit_transform(a_r10)
# e_r10 = to_categorical(i_r10,num_classes=len(r10))
# for i in range(len(r10)):
#   r_10[r10[i]] = list(e_r10[i])
# #11
# r11=[]
# r_11={}
# for row in X:
#   if row[11] not in r11:
#     r11.append(row[11]) 
# a_r11 = array(r11)
# i_r11 = label_encoder.fit_transform(a_r11)
# e_r11 = to_categorical(i_r11,num_classes=len(r11))
# for i in range(len(r11)):
#   r_11[r11[i]] = list(e_r11[i])
# #12
# r12=[]
# r_12={}
# for row in X:
#   if row[12] not in r12:
#     r12.append(row[12]) 
# a_r12 = array(r12)
# i_r12 = label_encoder.fit_transform(a_r12)
# e_r12 = to_categorical(i_r12,num_classes=len(r12))
# for i in range(len(r12)):
#   r_12[r12[i]] = list(e_r12[i])
# #13
# r13=[]
# r_13={}
# for row in X:
#   if row[13] not in r13:
#     r13.append(row[13]) 
# a_r13 = array(r13)
# i_r13 = label_encoder.fit_transform(a_r13)
# e_r13 = to_categorical(i_r13,num_classes=len(r13))
# for i in range(len(r13)):
#   r_13[r13[i]] = list(e_r13[i])
# #14
# r14=[]
# r_14={}
# for row in X:
#   if row[14] not in r14:
#     r14.append(row[14]) 
# a_r14 = array(r14)
# i_r14 = label_encoder.fit_transform(a_r14)
# e_r14 = to_categorical(i_r14,num_classes=len(r14))
# for i in range(len(r14)):
#   r_14[r14[i]] = list(e_r14[i])

# r_11

In [0]:
for row in X:
  for k,v in r_10.items():
        if k==row[10]:
            row[10]=v
            break
  for k,v in r_11.items():
        if k==row[11]:
            row[11]=v
            break


In [0]:
for row in X:
  for k,v in r_12.items():
        if k==row[12]:
            row[12]=v
            break
  for k,v in r_13.items():
        if k==row[13]:
            row[13]=v
            break
  for k,v in r_14.items():
        if k==row[14]:
            row[14]=v
            break


In [0]:
normalizer = MinMaxScaler(feature_range = (0,1))
x = X[:,0]
x = x.reshape(-1,1)
x = normalizer.fit_transform(x)
y = y.reshape(-1,1)
#y_norm = normalizer.fit_transform(y)
from keras.utils import np_utils 
nb_classes = 2
y_norm = np_utils.to_categorical(y, nb_classes) 
#y_norm[2,:]
for i in range(len(X)):
  X[i,0] = float(x[i])
  
X[10]

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([0.7838036809815953, 1, 708, 4815, 0, 1, 0, 7, 11, 0, 9, 10, 4, 7,
       10], dtype=object)

In [0]:
pre_X = []
pre_y = []
for i in range(10,len(y)):
  pre_X.append(X_norm[i-10:i,:])
  pre_y.append(y_norm[i,:])

pre_X = np.array(pre_X)
pre_y = np.array(pre_y)

model = Sequential()
model.add(Dense(100,input_dim=10,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(100,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(90,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(70,kernel_initializer = 'normal',activation='relu'))
model.add(Dense(1,kernel_initializer = 'normal',activation='sigmoid'))
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

model.fit(X_norm,y_norm,epochs=10,batch_size=100)

In [0]:
# model = Sequential()
# model.add(LSTM(units = 100,return_sequences=True,input_shape = (pre_X.shape[1],10)))
# model.add(Dropout(0.3))
# model.add(LSTM(units = 70,return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(units = 70,return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(units = 70))
# model.add(Dropout(0.2))
# model.add(Dense(units=2,activation='sigmoid'))
# model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

# model.fit(pre_X,pre_y,epochs=2,batch_size=100)
 

model = Sequential()
model.add(BatchNormalization())
model.add(Dense(200,input_dim=15,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(200,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(100,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(60,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(30,kernel_initializer = 'normal',activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(2,kernel_initializer = 'normal',activation='sigmoid'))
model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])

model.fit(X,y_norm,epochs=20,batch_size=50)

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
data = pd.read_csv('test_bqCt9Pv.csv')
print(len(data))
data = data.fillna(0)
print(len(data))
p_data = data.iloc[:,[3,9,19,33,34,35,36,37,38,39,4,5,6,11,12]]
print(len(p_data))
X_test = p_data.iloc[:,:15].values
X_test[0]

112392
112392
112392


array([86.54, 'Salaried', 0, 0, 0, 0, 0, '0yrs 0mon', '0yrs 0mon', 0, 67,
       22807, 45, 6, 1998], dtype=object)

In [0]:
for row in X_test:
    string = row[7]
    string = string.replace('yrs','')
    string = string.replace('mon','')
    s = string.split()
    string = int(s[0])*12+int(s[1])
    row[7] = string
    string = row[8]
    string = string.replace('yrs','')
    string = string.replace('mon','')
    s = string.split()
    string = int(s[0])*12+int(s[1])
    row[8] = string

In [0]:
for row in X_test:
  for k,v in r_10.items():
        if k==row[10]:
            row[10]=v
            break
  for k,v in r_11.items():
        if k==row[11]:
            row[11]=v
            break


In [0]:
for row in X_test:
  for k,v in r_12.items():
        if k==row[12]:
            row[12]=v
            break
  for k,v in r_13.items():
        if k==row[13]:
            row[13]=v
            break
  for k,v in r_14.items():
        if k==row[14]:
            row[14]=v
            break


In [0]:
print(e)
for row in X_test:
    for k,v in e.items():
        if k==row[1]:
            row[1]=v
X_test_norm = normalizer.fit_transform(X_test)

x = X_test[:,0]
x = x.reshape(-1,1)
x = normalizer.fit_transform(x)
for i in range(len(X_test)):
  X_test[i,0] = float(x[i])


X_test[0]

{'Self employed': 0, 'Salaried': 1}


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([0.9004354478051078, 1, 0, 0, 0, 0, 0, 0, 0, 0, 9, 508, 4, 7, 608],
      dtype=object)

In [0]:
pre_X_test = []
for i in range(10,len(X_test)):
  pre_X_test.append(X_test_norm[i-10:i,:])

pre_X_test = np.array(pre_X_test)

In [0]:
y_predict = model.predict(X_test)
#y_predict = normalizer.inverse_transform(y_predict)

In [0]:

print(y_predict[0])
pre_dict = np.argmax(y_predict,axis=1)
len(pre_dict)

[0.5836658  0.22917137]


112392

In [0]:
for row in pre_dict:
  if row != 0:
    print(row)

In [0]:
out =[]
for i in range(len(pre_dict)):
  out.append([data.iloc[i,0],pre_dict[i]])

In [0]:
out[100]

[756908, 0]

In [0]:

with open('sub1.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerow(['UniqueID','loan_default'])

csvFile.close()

In [0]:

with open('sub1.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(out)

csvFile.close()

In [0]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size = 0.20, random_state = 42)

In [0]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42,verbose=2,n_jobs=-1)
rf.fit(train_X, train_y)

In [0]:
predictions = rf.predict(test_X)
# Calculate the absolute errors
#errors = abs(predictions - test_y)
#print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
#mape = 100 * (errors / test_y)
# Calculate and display accuracy
#accuracy = 100 - np.mean(mape)
#print('Accuracy:', round(accuracy, 2), '%.')

In [0]:
pre = rf.predict(X_test_norm)

In [0]:
pre_out = []
for i in range(len(pre)):
  if pre[i] < 0.5:
    pre_out.append([data.iloc[i,0],0])
  else:
    pre_out.append([data.iloc[i,0],1])

In [0]:

with open('sub5.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerow(['UniqueID','loan_default'])

csvFile.close()

with open('sub5.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(pre_out)

csvFile.close()